version: '3'
services:
  server:
    image: rancher/k3s:v0.8.0
    command: server --disable-agent
    environment:
    - K3S_CLUSTER_SECRET=8Z6MXccyTKms1sZgU
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - wigm-k8s:/var/lib/rancher/k3s
    - .:/output
    ports:
    - 6443:6443

  node:
    image: rancher/k3s:v0.8.0
    tmpfs:
    - /run
    - /var/run
    privileged: true
    depends_on:
    - server
    environment:
    - K3S_URL=https://server:6443
    - K3S_CLUSTER_SECRET=8Z6MXccyTKms1sZgU

volumes:
  wigm-k8s: {}
