---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wigm-host-NAME
  labels:
    app: wigm
    gif: NAME
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wigm
      gif: NAME
  template:
    metadata:
      labels:
        app: wigm
        gif: NAME
    spec:
      containers:
      - name: gifhost
        image: nginx:1.15-alpine
        ports:
        - containerPort: 80
        env:
        - name: GIF_NAME
          value: NAME
        - name: GIF_SOURCE_LINK
          value: LINK
        command:
        - sh
        - -exc
        - |
          # get curl
          apk update && apk add curl

          # go to data dir
          cd /usr/share/nginx/html

          # fetch original
          curl -Lo wigm.gif "$GIF_SOURCE_LINK"

          # write page using heredoc
          cat > index.html <<EOF
          <head>
            <title>WIGM: $GIF_NAME</title>
          </head>
          <body>
            <h1>WIGM: $GIF_NAME</h1>
            <img src="wigm.gif" />
          </body>
          EOF

          # start nginx
          exec nginx -g "daemon off;"
---
kind: Service
apiVersion: v1
metadata:
  name: wigm-host-NAME
  labels:
    app: wigm
    gif: NAME
spec:
  selector:
    app: wigm
    gif: NAME
  # Uncomment line below to request
  # a cloud LB for the service
  # type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wigm-host-NAME
  labels:
    app: wigm
    gif: NAME
spec:
  rules:
  - host: NAME.wigm.carson-anderson.com
    http:
      paths:
      - path: /
        backend:
          serviceName: wigm-host-NAME
          servicePort: 80
