apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: wigmgifs.wigm.carson-anderson.com
spec:
  group: wigm.carson-anderson.com
  names:
    kind: WigmGif
    listKind: WigmGifList
    plural: wigmgifs
    singular: wigmgif
    # shortNames added manually
    shortNames:
    - wg
  scope: Namespaced
  version: v1
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: Title
    type: string
    description: The title of the gif
    JSONPath: .spec.gif.title
  - name: DeploymentRDY
    type: boolean
    description: Is the deployment ready
    JSONPath: .status.deployment.ready
  - name: ServiceCrtd
    type: boolean
    description: Is the service created
    JSONPath: .status.service.created
  - name: ServiceType
    type: string
    description: The type of service for the instance
    JSONPath: .status.service.type
  - name: IngressCrtd
    type: string
    description: The type of service for the instance
    JSONPath: .status.ingress.created
