apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: wigmgifs.wigm.carson-anderson.com
spec:
  group: wigm.carson-anderson.com
  names:
    kind: WigmGif
    listKind: WigmGifList
    plural: wigmgifs
    singular: wigmgif
    shortNames:
    - wg
  scope: Namespaced
  version: v1
  subresources:
    status: {}
